# Generated by Django 5.2.15 on 2026-06-17 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("취업", "취업"),
                            ("진로", "진로"),
                            ("인간관계", "인간관계"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("취업", "취업"),
                            ("진로", "진로"),
                            ("인간관계", "인간관계"),
                            ("일반", "일반"),
                        ],
                        default="일반",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "author",
                    models.CharField(blank=True, default="작자 미상", max_length=50),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnalysisLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chosen_question", models.TextField()),
                ("user_answer", models.TextField()),
                ("predicted_category", models.CharField(max_length=20)),
                ("ai_solution", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
