# Generated by Django 5.2.15 on 2026-06-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counseling", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="category",
        ),
        migrations.AddField(
            model_name="analysislog",
            name="anxiety_score",
            field=models.IntegerField(default=0, verbose_name="불안 지수"),
        ),
        migrations.AddField(
            model_name="analysislog",
            name="depression_score",
            field=models.IntegerField(default=0, verbose_name="우울 지수"),
        ),
        migrations.AddField(
            model_name="analysislog",
            name="matched_guide",
            field=models.TextField(
                blank=True, null=True, verbose_name="매칭된 내부 가이드라인"
            ),
        ),
        migrations.AddField(
            model_name="analysislog",
            name="urgency_score",
            field=models.IntegerField(default=0, verbose_name="조급 지수"),
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.CharField(
                choices=[("취업", "취업"), ("진로", "진로"), ("인간관계", "인간관계")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="author",
            field=models.CharField(default="작자 미상", max_length=50),
        ),
    ]
