# Generated by Django 5.2.15 on 2026-06-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counseling", "0002_remove_quote_category_analysislog_anxiety_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysislog",
            name="growth_score",
            field=models.IntegerField(default=0, verbose_name="성장 의지 지수"),
        ),
        migrations.AddField(
            model_name="analysislog",
            name="stability_score",
            field=models.IntegerField(default=0, verbose_name="안정/감사 지수"),
        ),
    ]
